
 EVP_PKEY_CTX *pctx = EVP_PKEY_CTX_new_id(EVP_PKEY_HKDF, NULL);

The total length of the info buffer cannot exceed 2048 bytes in length: this
should be more than enough for any normal use of HKDF.

The output length of an HKDF expand operation is specified via the length
parameter to the L<EVP_PKEY_derive(3)> function.

=head1 COPYRIGHT

Copyright 2016-2022 The OpenSSL Project Authors. All Rights Reserved.

Licensed under the Apache License 2.0 (the "License").  You may not use
this file except in compliance with the License.  You can obtain a copy
in the file LICENSE in the source distribution or at