
=item "AES-128-ECB", "AES-192-ECB" and "AES-256-ECB"

=item "AES-192-OCB", "AES-128-OCB" and "AES-256-OCB"

=item "AES-128-SIV", "AES-192-SIV" and "AES-256-SIV"

=item "AES-128-XTS" and "AES-256-XTS"

=over 4

=item "AES-128-OFB", "AES-192-OFB" and "AES-256-OFB"

=back

=head2 Parameters

=head1 COPYRIGHT

Copyright 2021 The OpenSSL Project Authors. All Rights Reserved.

Licensed under the Apache License 2.0 (the "License").  You may not use
this file except in compliance with the License.  You can obtain a copy
in the file LICENSE in the source distribution or at