
=over 4

=item any subject name in I<ctx> set via L<OSSL_CMP_CTX_set1_subjectName(3)> -
if it is the NULL-DN (i.e., any empty sequence of RDNs), no subject is included,

=item the subject field of any PKCS#10 CSR set in I<ctx>
via L<OSSL_CMP_CTX_set1_p10CSR(3)>,

=item the subject field of any reference certificate given in I<ctx>
(see L<OSSL_CMP_CTX_set1_oldCert(3)>), but only if I<for_KUR> is nonzero
or the I<ctx> does not include a Subject Alternative Name.

=back


=item the public key derived from any key set via L<OSSL_CMP_CTX_set0_newPkey(3)>,

=item the public key of any PKCS#10 CSR given in I<ctx>,

=item the public key of any reference certificate given in I<ctx>,

=item the public key derived from any client's private key
set via L<OSSL_CMP_CTX_set1_pkey(3)>.


OSSL_CMP_MSG_get_bodytype() returns the body type or -1 on error.

OSSL_CMP_CTX_setup_CRM() returns a pointer to a B<OSSL_CRMF_MSG> on success,
NULL on error.

d2i_OSSL_CMP_MSG_bio() returns the parsed message or NULL on error.


OSSL_CMP_MSG_update_transactionID() returns 1 on success, 0 on error.

=head1 SEE ALSO

L<OSSL_CMP_CTX_set1_subjectName(3)>, L<OSSL_CMP_CTX_set1_p10CSR(3)>,
L<OSSL_CMP_CTX_set1_oldCert(3)>, L<OSSL_CMP_CTX_set0_newPkey(3)>,
L<OSSL_CMP_CTX_set1_pkey(3)>, L<OSSL_CMP_CTX_set0_reqExtensions(3)>,
L<OSSL_CMP_CTX_push1_subjectAltName(3)>, L<OSSL_CMP_CTX_push0_policy(3)>

=head1 HISTORY

The OpenSSL CMP support was added in OpenSSL 3.0.
