
					...
					module aes0_wrapper #(...)(...);
					...
						
						input logic     acct_ctrl_i;
						
					...
						
						axi_lite_interface #(...
						) axi_lite_interface_i (
						...
							
							.en_o       ( en_acct    ),
							
						
					...
					..);
						
						assign en = en_acct && acct_ctrl_i;
						
					...
					endmodule
					...
					module clint #(...)(...);
					...
						
						axi_lite_interface #(...
						) axi_lite_interface_i (
						...
							
							.en_o       ( en         ),
							
						
					...
					  );
					...
					endmodule
					
					